name: 'kafka'
version: 0.1.0
description: Kafka Client library for Dartlang
homepage: https://github.com/pulyaevskiy/dart-kafka
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.1
  logging: ^1.0.1

dev_dependencies:
  test:
  mockito: ^5.0.13
