name: 'kafka'
version: 0.1.0
description: Kafka Client library for Dartlang
homepage: https://github.com/pulyaevskiy/dart-kafka
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  quiver: ^2.1.3
  logging: "^0.11.4"

dev_dependencies:
  test: "^1.15.3"
  mockito: "^4.1.1"
  dart_coveralls: "^0.6.0+4"
